export const securityTools = {
  suricata: {
    name: 'Suricata',
    command: 'sudo',
    args: ['suricata', '-c', '/etc/suricata/suricata.yaml', '-i', 'eth0'],
    message: 'Do you want to run Suricata for intrusion detection?',
    checkCommand: 'suricata --version',
    explanation: 'Suricata is monitoring network traffic in real-time, analyzing packets for potential threats and intrusions. It\'s comparing packet contents against a database of known attack signatures and abnormal behaviors.',
  },
  zeek: {
    name: 'Zeek',
    command: 'sudo',
    args: ['zeek', '-i', 'eth0'],
    message: 'Do you want to run Zeek for network analysis?',
    checkCommand: 'zeek --version',
    explanation: 'Zeek is performing a deep analysis of network traffic, creating detailed logs of network activities. It\'s looking at application-layer content to understand the context of communications.',
  },
  nmap: {
    name: 'Nmap',
    command: 'sudo',
    args: ['nmap', '-sV', '-O'],
    message: 'Do you want to run an Nmap scan for vulnerability assessment?',
    additionalPrompt: {
      type: 'input',
      name: 'nmapTarget',
      message: 'Enter the IP range for Nmap scan (e.g., 192.168.1.0/24):',
    },
    checkCommand: 'nmap --version',
    explanation: 'Nmap is scanning the specified IP range, probing for open ports, identifying services running on those ports, and attempting to determine the operating systems of the target devices.',
  },
  tripwire: {
    name: 'Tripwire',
    command: 'sudo',
    args: ['tripwire', '--check'],
    message: 'Do you want to run Tripwire for file integrity checking?',
    checkCommand: 'tripwire --version',
    explanation: 'Tripwire is checking the integrity of critical system files and directories. It\'s comparing the current state of these files against a known-good baseline to detect any unauthorized changes.',
  },
  rkhunter: {
    name: 'rkhunter',
    command: 'sudo',
    args: ['rkhunter', '--check'],
    message: 'Do you want to run rkhunter for rootkit detection?',
    checkCommand: 'rkhunter --version',
    explanation: 'Rkhunter is scanning the system for signs of rootkits, backdoors, and local exploits. It\'s checking for hidden files, suspicious file permissions, and known rootkit signatures.',
  },
  clamav: {
    name: 'ClamAV',
    command: 'sudo',
    args: ['clamscan', '-r', '/'],
    message: 'Do you want to run ClamAV for malware scanning?',
    checkCommand: 'clamscan --version',
    explanation: 'ClamAV is performing a recursive scan of the entire file system, checking files against a database of known malware signatures. It\'s looking for viruses, trojans, malware, and other malicious content.',
  },
  tshark: {
    name: 'tshark',
    command: 'sudo',
    args: ['tshark', '-i', 'eth0'],
    message: 'Do you want to capture network traffic with tshark?',
    additionalPrompt: {
      type: 'input',
      name: 'tsharkDuration',
      message: 'Enter the duration for tshark capture (in seconds):',
      validate: (value) => !isNaN(value) || 'Please enter a number',
    },
    checkCommand: 'tshark --version',
    explanation: 'Tshark is capturing and analyzing network packets in real-time. It\'s recording detailed information about all network traffic, including source and destination addresses, protocols used, and packet contents.',
  },
};
